@api = http://localhost:3000/tasks
GET {{api}}
###
GET {{api}}/5
###
GET {{api}}/count
###
POST {{api}}
Content-Type: application/json

{
    "title": "Learn about Jira",
    "description": "I want to learn about Jira for test"
}

###
DELETE {{api}}/5

###
PUT {{api}}/7
Content-Type: application/json

{
    "title": "Learn about Anywhere",
    "description": "I want to learn about Selenium with Java"
}